import { ProjectMemberRoleDtoRole } from "../api/generated";

export type ProjectAbilitiesKeys =
  | "RENAME_PROJECT"
  | "CREATE_INVITE_LINK"
  | "DELETE_INVITE_LINK"
  | "MEMBER_CONTROL"
  | "CREATE_BOARD"
  | "RENAME_BOARD"
  | "ARCHIVE_BOARD"
  | "CREATE_LIST"
  | "RENAME_LIST"
  | "ARCHIVE_LIST"
  | "CREATE_TAG"
  | "EDIT_TAG"
  | "DELETE_TAG"
  | "ATTACH_TAG"
  | "DETACH_TAG"
  | "CREATE_CARD"
  | "RENAME_CARD"
  | "EDIT_DESCRIPTION"
  | "ARCHIVE_CARD"
  | "ATTACH_FILE"
  | "DETACH_FILE"
  | "SET_CARD_STATUS"
  | "SET_CARD_COVER"
  | "SET_CARD_DEADLINE";

export const PROJECT_ABILITIES: Record<
  ProjectAbilitiesKeys,
  ProjectMemberRoleDtoRole[]
> = {
  RENAME_PROJECT: ["ADMIN"],
  CREATE_INVITE_LINK: ["ADMIN"],
  DELETE_INVITE_LINK: ["ADMIN"],

  MEMBER_CONTROL: ["ADMIN"],

  CREATE_BOARD: ["ADMIN"],
  RENAME_BOARD: ["ADMIN"],
  ARCHIVE_BOARD: ["ADMIN"],

  CREATE_LIST: ["ADMIN"],
  RENAME_LIST: ["ADMIN"],
  ARCHIVE_LIST: ["ADMIN"],

  CREATE_TAG: ["ADMIN"],
  EDIT_TAG: ["ADMIN"],
  DELETE_TAG: ["ADMIN"],

  ATTACH_TAG: ["ADMIN", "MEMBER"],
  DETACH_TAG: ["ADMIN", "MEMBER"],

  CREATE_CARD: ["ADMIN", "MEMBER"],
  RENAME_CARD: ["ADMIN", "MEMBER"],
  EDIT_DESCRIPTION: ["ADMIN", "MEMBER"],
  ARCHIVE_CARD: ["ADMIN", "MEMBER"],

  ATTACH_FILE: ["ADMIN", "MEMBER"],
  DETACH_FILE: ["ADMIN", "MEMBER"],

  SET_CARD_STATUS: ["ADMIN", "MEMBER"],
  SET_CARD_COVER: ["ADMIN", "MEMBER"],
  SET_CARD_DEADLINE: ["ADMIN", "MEMBER"],
};
